/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as MapRouteImport } from './routes/map'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryIdRouteImport } from './routes/history.$id'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HistoryRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/history': typeof HistoryRouteWithChildren
  '/map': typeof MapRoute
  '/summary': typeof SummaryRoute
  '/api/chat': typeof ApiChatRoute
  '/history/$id': typeof HistoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/history': typeof HistoryRouteWithChildren
  '/map': typeof MapRoute
  '/summary': typeof SummaryRoute
  '/api/chat': typeof ApiChatRoute
  '/history/$id': typeof HistoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/history': typeof HistoryRouteWithChildren
  '/map': typeof MapRoute
  '/summary': typeof SummaryRoute
  '/api/chat': typeof ApiChatRoute
  '/history/$id': typeof HistoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/history'
    | '/map'
    | '/summary'
    | '/api/chat'
    | '/history/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/history'
    | '/map'
    | '/summary'
    | '/api/chat'
    | '/history/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/chat'
    | '/history'
    | '/map'
    | '/summary'
    | '/api/chat'
    | '/history/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  MapRoute: typeof MapRoute
  SummaryRoute: typeof SummaryRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HistoryRouteChildren {
  HistoryIdRoute: typeof HistoryIdRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistoryIdRoute: HistoryIdRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  HistoryRoute: HistoryRouteWithChildren,
  MapRoute: MapRoute,
  SummaryRoute: SummaryRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
