/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as PretestResultsRouteImport } from './routes/pretest-results'
import { Route as PretestRouteImport } from './routes/pretest'
import { Route as MapRouteImport } from './routes/map'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as FinalTestRouteImport } from './routes/final-test'
import { Route as FinalAnalysisRouteImport } from './routes/final-analysis'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CourseRouteImport } from './routes/course'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryIdRouteImport } from './routes/history.$id'
import { Route as FinalAnalysisIdRouteImport } from './routes/final-analysis.$id'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const PretestResultsRoute = PretestResultsRouteImport.update({
  id: '/pretest-results',
  path: '/pretest-results',
  getParentRoute: () => rootRouteImport,
} as any)
const PretestRoute = PretestRouteImport.update({
  id: '/pretest',
  path: '/pretest',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalTestRoute = FinalTestRouteImport.update({
  id: '/final-test',
  path: '/final-test',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalAnalysisRoute = FinalAnalysisRouteImport.update({
  id: '/final-analysis',
  path: '/final-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseRoute = CourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HistoryRoute,
} as any)
const FinalAnalysisIdRoute = FinalAnalysisIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FinalAnalysisRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/course': typeof CourseRoute
  '/dashboard': typeof DashboardRoute
  '/final-analysis': typeof FinalAnalysisRouteWithChildren
  '/final-test': typeof FinalTestRoute
  '/flashcards': typeof FlashcardsRoute
  '/history': typeof HistoryRouteWithChildren
  '/learn': typeof LearnRoute
  '/map': typeof MapRoute
  '/pretest': typeof PretestRoute
  '/pretest-results': typeof PretestResultsRoute
  '/summary': typeof SummaryRoute
  '/api/chat': typeof ApiChatRoute
  '/final-analysis/$id': typeof FinalAnalysisIdRoute
  '/history/$id': typeof HistoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/course': typeof CourseRoute
  '/dashboard': typeof DashboardRoute
  '/final-analysis': typeof FinalAnalysisRouteWithChildren
  '/final-test': typeof FinalTestRoute
  '/flashcards': typeof FlashcardsRoute
  '/history': typeof HistoryRouteWithChildren
  '/learn': typeof LearnRoute
  '/map': typeof MapRoute
  '/pretest': typeof PretestRoute
  '/pretest-results': typeof PretestResultsRoute
  '/summary': typeof SummaryRoute
  '/api/chat': typeof ApiChatRoute
  '/final-analysis/$id': typeof FinalAnalysisIdRoute
  '/history/$id': typeof HistoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/course': typeof CourseRoute
  '/dashboard': typeof DashboardRoute
  '/final-analysis': typeof FinalAnalysisRouteWithChildren
  '/final-test': typeof FinalTestRoute
  '/flashcards': typeof FlashcardsRoute
  '/history': typeof HistoryRouteWithChildren
  '/learn': typeof LearnRoute
  '/map': typeof MapRoute
  '/pretest': typeof PretestRoute
  '/pretest-results': typeof PretestResultsRoute
  '/summary': typeof SummaryRoute
  '/api/chat': typeof ApiChatRoute
  '/final-analysis/$id': typeof FinalAnalysisIdRoute
  '/history/$id': typeof HistoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/course'
    | '/dashboard'
    | '/final-analysis'
    | '/final-test'
    | '/flashcards'
    | '/history'
    | '/learn'
    | '/map'
    | '/pretest'
    | '/pretest-results'
    | '/summary'
    | '/api/chat'
    | '/final-analysis/$id'
    | '/history/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/course'
    | '/dashboard'
    | '/final-analysis'
    | '/final-test'
    | '/flashcards'
    | '/history'
    | '/learn'
    | '/map'
    | '/pretest'
    | '/pretest-results'
    | '/summary'
    | '/api/chat'
    | '/final-analysis/$id'
    | '/history/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/chat'
    | '/course'
    | '/dashboard'
    | '/final-analysis'
    | '/final-test'
    | '/flashcards'
    | '/history'
    | '/learn'
    | '/map'
    | '/pretest'
    | '/pretest-results'
    | '/summary'
    | '/api/chat'
    | '/final-analysis/$id'
    | '/history/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  CourseRoute: typeof CourseRoute
  DashboardRoute: typeof DashboardRoute
  FinalAnalysisRoute: typeof FinalAnalysisRouteWithChildren
  FinalTestRoute: typeof FinalTestRoute
  FlashcardsRoute: typeof FlashcardsRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  LearnRoute: typeof LearnRoute
  MapRoute: typeof MapRoute
  PretestRoute: typeof PretestRoute
  PretestResultsRoute: typeof PretestResultsRoute
  SummaryRoute: typeof SummaryRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pretest-results': {
      id: '/pretest-results'
      path: '/pretest-results'
      fullPath: '/pretest-results'
      preLoaderRoute: typeof PretestResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pretest': {
      id: '/pretest'
      path: '/pretest'
      fullPath: '/pretest'
      preLoaderRoute: typeof PretestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/final-test': {
      id: '/final-test'
      path: '/final-test'
      fullPath: '/final-test'
      preLoaderRoute: typeof FinalTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/final-analysis': {
      id: '/final-analysis'
      path: '/final-analysis'
      fullPath: '/final-analysis'
      preLoaderRoute: typeof FinalAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course': {
      id: '/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/final-analysis/$id': {
      id: '/final-analysis/$id'
      path: '/$id'
      fullPath: '/final-analysis/$id'
      preLoaderRoute: typeof FinalAnalysisIdRouteImport
      parentRoute: typeof FinalAnalysisRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FinalAnalysisRouteChildren {
  FinalAnalysisIdRoute: typeof FinalAnalysisIdRoute
}

const FinalAnalysisRouteChildren: FinalAnalysisRouteChildren = {
  FinalAnalysisIdRoute: FinalAnalysisIdRoute,
}

const FinalAnalysisRouteWithChildren = FinalAnalysisRoute._addFileChildren(
  FinalAnalysisRouteChildren,
)

interface HistoryRouteChildren {
  HistoryIdRoute: typeof HistoryIdRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistoryIdRoute: HistoryIdRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  CourseRoute: CourseRoute,
  DashboardRoute: DashboardRoute,
  FinalAnalysisRoute: FinalAnalysisRouteWithChildren,
  FinalTestRoute: FinalTestRoute,
  FlashcardsRoute: FlashcardsRoute,
  HistoryRoute: HistoryRouteWithChildren,
  LearnRoute: LearnRoute,
  MapRoute: MapRoute,
  PretestRoute: PretestRoute,
  PretestResultsRoute: PretestResultsRoute,
  SummaryRoute: SummaryRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
